// 
//  Diploma of Interactive Gaming 
//  Game Development Faculty 
//  Media Design School 
//  Auckland
//  New Zealand
// 
//  (c) 2005-2010 Media Design School
//
//  File Name   :   input.h
//  Description :   Declaration for CInput
//  Author      :   Carsten Scholz
//  Mail        :   carsten.scholz@mediadesign.school.nz
//

#ifndef __IGFEB10_MODULE_INPUT_H__
#define __IGFEB10_MODULE_INPUT_H__

// Library Includes

// Local Includes

// Types
#define VIBRATION_MODIFIER ((uint16)(-1))

// Prototypes
enum EControl
{
	//Player Controls
	CONTROL_SHOOT,
	CONTROL_MOVEUP,
	CONTROL_MOVEDOWN,
	CONTROL_MOVERIGHT,
	CONTROL_MOVELEFT,	
	CONTROL_TURRETLEFT,
	CONTROL_TURRETRIGHT,
	CONTROL_EMP,
	CONTROL_MINE,
	CONTROL_PAUSE,
	CONTROL_EXIT,
	CONTROL_SCOUT,

	//Menu Controls
	CONTROL_SELECT,
	CONTROL_NAVIGATEUP,
	CONTROL_NAVIGATEDOWN,
	CONTROL_NAVIGATELEFT,
	CONTROL_NAVIGATERIGHT,
	CONTROL_BACK,

	//Debug Controls
	//DEBUG CAMERA
#ifdef _DEBUG
	CONTROL_ENABLE_DEBUG_CAMERA,
	CONTROL_CAMERALEFT,
	CONTROL_CAMERARIGHT,
	CONTROL_CAMERAFORWARD,
	CONTROL_CAMERABACK,
	CONTROL_CAMERAUP,
	CONTROL_CAMERADOWN,
	CONTROL_CAMERAYAWLEFT,
	CONTROL_CAMERAYAWRIGHT,
	CONTROL_CAMERAPITCHUP,
	CONTROL_CAMERAPITCHDOWN,
	CONTROL_CAMERAROLLLEFT,
	CONTROL_CAMERAROLLRIGHT,

	//CHEATS
	CONTROL_CHEATINVINC,
	CONTROL_CHEATNEVEREND,
	CONTROL_CHEATINVIS,
	CONTROL_CHEATSHEILD,
	CONTROL_CHEATFLAGCAPTURE,
	CONTROL_CHEATPIC,

	CONTROL_PLAYER1,
	CONTROL_PLAYER2,
	CONTROL_PLAYER3,
	CONTROL_PLAYER4,
	CONTROL_PLAYER5,
	CONTROL_PLAYER6,

	// Toggle debug window.
	CONTROL_ENABLE_DEBUG_WINDOW
#endif // _DEBUG
};

enum EMotor
{
	MOTOR_RIGHT = 0x1,
	MOTOR_LEFT = 0x2,
	MOTOR_BOTH = MOTOR_RIGHT | MOTOR_LEFT,
};

#endif // __IGFEB10_MODULE_INPUT_H__

